name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'etc/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        emacs_version:
          - "24.4"
          - "24.5"
          - "25.1"
          - "25.2"
          - "25.3"
          - "26.1"
          - "26.2"
          - "26.3"
          - "27.1"
          - snapshot
        include:
          - emacs_version: "24.4"
            allow_failure: true
          - emacs_version: "24.5"
            allow_failure: true
          - emacs_version: snapshot
            allow_failure: true
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make test'
    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'
